import MainLayout from "@/lib/@components/MainLayout";
import { Text } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>codeisneverodd</title>
        <meta
          name="description"
          content="Generated by nextjs-chakra-template"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout title="Home">
        <Text>New Template</Text>
      </MainLayout>
    </>
  );
}
